import type { Metadata } from "next";
import "../../../globals.css";
export const metadata: Metadata = {
  title: "downloads",
  description: "Generated by create next app",
};

export default function UserDownloadsLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      {children}
    </>
  );
}
