import type { Metadata } from "next";
import "../../../../globals.css";
import { CategoryContextProvider } from "@/context/useAdminCategory";

export const metadata: Metadata = {
  title: "Dashboard",
  description: "Generated by create next app",
};

export default function CategoryLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <CategoryContextProvider>{children}</CategoryContextProvider>
    </>
  );
}
