import type { Metadata } from "next";
import "@/app/globals.css";
import React from "react";
import { VectorFilterContextProvider } from "@/context/useVectorFilter";
import { VectorsDataContextProvider } from "@/context/useVectorsData";
import { VectorModalContextProvider } from "@/context/useVectorModal";
export const metadata: Metadata = {
  title: "vectors",
  description: "Generated by create next app",
};

export default function VectorsLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div>
      <VectorsDataContextProvider>
        <VectorModalContextProvider>
        <VectorFilterContextProvider>
          {children}
        </VectorFilterContextProvider>
        </VectorModalContextProvider>
      </VectorsDataContextProvider>
    </div>
  );
}
