import type { Metadata } from "next";
import "../../globals.css";
export const metadata: Metadata = {
  title: "profile",
  description: "Generated by create next app",
};

export default function ProfilesRootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      {children}
    </>
  );
}
