import type { Metadata } from "next";
import "../../globals.css";
import { LoggedInUserContextProvider } from "@/context/useLoggedInUser";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <LoggedInUserContextProvider>{children}</LoggedInUserContextProvider>
    </>
  );
}
