import type { Metadata } from "next";
import "../../../../globals.css";
 import { AdminVectorsContextProvider } from "@/context/useAdminVectors";

export const metadata: Metadata = {
  title: "Dashboard",
  description: "Generated by create next app",
};

export default function TagsLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <AdminVectorsContextProvider>{children}</AdminVectorsContextProvider>
    </>
  );
}
