import type { Metadata } from "next";
import "../../../../../globals.css";


export const metadata: Metadata = {
  title: "Dashboard",
  description: "Generated by create next app",
};

export default function ImagesLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      {children}
    </>
  );
}
