import type { Metadata } from "next";
import "@/app/globals.css";
export const metadata: Metadata = {
  title: "premium",
  description: "Generated by create next app",
};

export default function PremiumLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return <main className="bg-white">{children}</main>;
}
