import type { Metadata } from "next";
import "@/app/globals.css";
import React from "react";

export const metadata: Metadata = {
  title: "videos",
  description: "Generated by create next app",
};

export default function VideosLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
          {children}
    </>
  );
}
