import type { Metadata } from "next";
import "../../../globals.css";
import React from "react";
import { TabContextProvider } from "@/context/useTab";
export const metadata: Metadata = {
  title: "Home",
  description: "Generated by create next app",
};

export default function HomeLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <main className="bg-white">
      <TabContextProvider>
        {children}
      </TabContextProvider>
    </main>
  );
}
