import type { Metadata } from "next";
import "../../../../globals.css";
import { TagsContextProvider } from "@/context/useAdminTags";

export const metadata: Metadata = {
  title: "Dashboard",
  description: "Generated by create next app",
};

export default function TagsLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <TagsContextProvider>{children}</TagsContextProvider>
    </>
  );
}
