import type { Metadata } from "next";
import "../../../../../globals.css";
import {AdminVideosContextProvider} from "@/context/useAdminVideos";
 

export const metadata: Metadata = {
  title: "Dashboard",
  description: "Generated by create next app",
};

export default function VideosLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <AdminVideosContextProvider>
      {children}
    </AdminVideosContextProvider>
  );
}
