import type { Metadata } from "next";
import "./globals.css";
import { Open_Sans } from "next/font/google";
import { ThemeConfig } from "flowbite-react";
import { ThemeModeScript } from "flowbite-react";
const open_sans=Open_Sans({
  variable:"--font-open-sans",
  subsets:["latin"],
  weight:["400","700"]
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
        <head>
          <ThemeModeScript />
        </head>
        <body className={`${open_sans.variable}  antialiased`}>
          <ThemeConfig dark={false} />
            {children}
        </body>
    </html>
  );
}
