import type { Metadata } from "next";
import "./globals.css";
import { Poppins } from "next/font/google";
import { ThemeConfig } from "flowbite-react";
import { ThemeModeScript } from "flowbite-react";

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      
        <head>
          <ThemeModeScript />
        </head>
        <body className={`${poppins.variable}  antialiased`}>
          <ThemeConfig dark={false} />
            {children}
        </body>
    </html>
  );
}
