import type { Metadata } from "next";
import "../../../../globals.css";
import { Fragment } from "react";
 

export const metadata: Metadata = {
  title: "Users",
  description: "Generated by create next app",
};

export default function TagsLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <Fragment>
      {children}
    </Fragment>
  );
}
