import type { Metadata } from "next";
import "../../../globals.css";
export const metadata: Metadata = {
  title: "projects",
  description: "Generated by create next app",
};

export default function ProjectsLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return <>{children}</>;
}
